export const QUERY_KEY = {
  USER: {
    KEY: 'USER',
    GET_USER_LIST: 'GET_USER_LIST',
    GET_PROFILE: 'GET_PROFILE',
    GET_USER_DETAIL: 'GET_USER_DETAIL',
    GET_PERMISSION: 'GET_PERMISSION',
  },
  GENRE: {
    KEY: 'GENRE',
    GET_GENRE_LIST: 'GET_GENRE_LIST',
    GET_GENRE_DETAIL: 'GET_GENRE_DETAIL',
  },
  THEME: {
    KEY: 'THEME',
    GET_THEME_LIST: 'GET_THEME_LIST',
    GET_THEME_LIST_SELECT: 'GET_THEME_LIST_SELECT',
    GET_THEME_DETAIL: 'GET_THEME_DETAIL',
  },
  FILE_TYPE: {
    KEY: 'FILE_TYPE',
    GET_FILE_TYPE_LIST: 'GET_FILE_TYPE_LIST',
    GET_FILE_TYPE_DETAIL: 'GET_FILE_TYPE_DETAIL',
  },
  SONG: {
    KEY: 'SONG',
    GET_SONG_LIST: 'GET_SONG_LIST',
    GET_SONG_LIST_SELECT: 'GET_SONG_LIST_SELECT',
    GET_SONG_DETAIL: 'GET_SONG_DETAIL',
    GET_SONG_EXIST_DETAIL: 'GET_SONG_EXIST_DETAIL',
  },
};
