export const QUERY_KEY = {
  USER: {
    KEY: 'USER',
    GET_USER_LIST: 'GET_USER_LIST',
    GET_PROFILE: 'GET_PROFILE',
    GET_USER_DETAIL: 'GET_USER_DETAIL',
    GET_PERMISSION: 'GET_PERMISSION',
  },
  GENRE: {
    KEY: 'GENRE',
    GET_GENRE_LIST: 'GET_GENRE_LIST',
    GET_GENRE_DETAIL: 'GET_GENRE_DETAIL',
  },
  THEME: {
    KEY: 'THEME',
    GET_THEME_LIST: 'GET_THEME_LIST',
    GET_THEME_DETAIL: 'GET_THEME_DETAIL',
  },
};
