import { QUERY_KEY } from '@/constants';

export const playlistQueryKeys = {
  all: QUERY_KEY.PLAYLIST.KEY,
  getList: [QUERY_KEY.PLAYLIST.KEY, QUERY_KEY.PLAYLIST.GET_PLAYLIST_LIST],
  getDataSidebar: [QUERY_KEY.PLAYLIST.KEY, QUERY_KEY.PLAYLIST.GET_DATA_SIDEBAR],
  getDetail: [QUERY_KEY.PLAYLIST.KEY, QUERY_KEY.PLAYLIST.GET_PLAYLIST_DETAIL],
};
